# Generated by Django 3.2.19 on 2023-06-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopScorer',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=264)),
                ('goals', models.PositiveIntegerField()),
                ('team', models.CharField(max_length=264)),
            ],
        ),
    ]
