# Generated by Django 3.2.19 on 2023-06-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0003_topscorer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top_5_league_attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Player', models.CharField(max_length=264)),
                ('Nation', models.CharField(max_length=264)),
                ('Pos', models.CharField(max_length=264)),
                ('Squad', models.CharField(max_length=264)),
                ('Age', models.IntegerField()),
                ('Born', models.BigIntegerField()),
                ('MP', models.BigIntegerField()),
                ('Starts', models.BigIntegerField()),
                ('Min', models.BigIntegerField()),
                ('Ninety_minutes_played', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Gls', models.BigIntegerField()),
                ('Ast', models.BigIntegerField()),
                ('GA', models.BigIntegerField()),
                ('GminusPK', models.BigIntegerField()),
                ('PK', models.BigIntegerField()),
                ('PKatt', models.BigIntegerField()),
                ('CrdY', models.BigIntegerField()),
                ('CrdR', models.BigIntegerField()),
                ('xG', models.DecimalField(decimal_places=2, max_digits=10)),
                ('npxG', models.DecimalField(decimal_places=2, max_digits=10)),
                ('xAG', models.DecimalField(decimal_places=2, max_digits=10)),
                ('npxGxAG', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PrgC', models.BigIntegerField()),
                ('PrgP', models.BigIntegerField()),
                ('PrgR', models.BigIntegerField()),
                ('Glsp90', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Astp90', models.DecimalField(decimal_places=2, max_digits=10)),
                ('GAp90', models.DecimalField(decimal_places=2, max_digits=10)),
                ('GminusPKp90', models.DecimalField(decimal_places=2, max_digits=10)),
                ('GAminusPKp90', models.DecimalField(decimal_places=2, max_digits=10)),
                ('xGp90', models.DecimalField(decimal_places=2, max_digits=10)),
                ('xAGp90', models.DecimalField(decimal_places=2, max_digits=10)),
                ('xGxAGp90', models.DecimalField(decimal_places=2, max_digits=10)),
                ('npxGp90', models.DecimalField(decimal_places=2, max_digits=10)),
                ('npxGxAGp90', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='TopScorer',
        ),
    ]
