# Generated by Django 3.2.19 on 2023-06-22 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0004_auto_20230622_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='top_5_league_attack',
            options={'verbose_name': 'Top_5_league_attack'},
        ),
    ]
