# Generated by Django 3.2.19 on 2023-06-22 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0005_alter_top_5_league_attack_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Top_5_league_attack',
        ),
    ]
